kind: List
apiVersion: v1
items:
# to be dropped already created by operator: https://github.com/masayag/must-gather-operator/blob/master/deploy/service_account.yaml
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: must-gather-operator
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"must-gather-operator"}}'
- apiVersion: v1
  kind: Route
  metadata:
    name: must-gather-operator
  spec:
    to:
      kind: Service
      name: must-gather-operator
    tls:
      termination: Reencrypt
- apiVersion: v1
  kind: Service
  metadata:
    name: must-gather-operator
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: must-gather-operator-tls
  spec:
    ports:
    - name: must-gather-operator
      port: 443
      targetPort: 8443
    selector:
      app: must-gather-operator
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: must-gather-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: must-gather-operator
    template:
      metadata:
        labels:
          app: must-gather-operator
      spec:
        serviceAccountName: must-gather-operator
        containers:
        - name: oauth-proxy
          image: openshift/oauth-proxy:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
            name: public
          args:
          - --https-address=:8443
          - --provider=openshift
          - --openshift-service-account=must-gather-operator
          - --upstream=http://localhost:8080
          - --tls-cert=/etc/tls/private/tls.crt
          - --tls-key=/etc/tls/private/tls.key
          - --cookie-secret=SECRET
          # Allows access if the user can view the service 'kubelet' in namespace 'kube-system' (administrators only)
          - --openshift-sar={"namespace":"kube-system","resource":"services","name":"kubelet","verb":"get"}
          volumeMounts:
          - mountPath: /etc/tls/private
            name: must-gather-operator-tls
        - name: nginx
          # Image source might change. 
          image: bitnami/nginx
          ports:
          - containerPort: 8080     
        volumes:
        - name: must-gather-operator-tls
          secret:
            secretName: must-gather-operator-tls